---
- hosts: server
  gather_facts: no
  sudo: no
  vars:
    user: dev
    password: $6$x.95LIU4dS$4WLX7ATLFUkAwMtTAJqrIcchJPIJZgsNQ1iUhyNrzOqvyr0P3QhcP5V8WLWrsFEZOlPV7aTAownXqzLmlul6x1

  tasks:

  - name: create group
    group: name={{user}} state=present
    tags: setup

  - name: create user
    user: name={{user}} state=present home=/home/{{user}} group={{user}} groups="sudo" password={{ password }} shell=/bin/bash
    tags: setup

  - name: install debian packages
    apt: pkg={{ item }} state=present update_cache=yes
    with_items:
    - git
    sudo: yes
    tags: setup

  - shell: curl -sSL https://get.docker.com/ubuntu/ | sudo sh
    sudo: yes
    tags: setup

  - command: adduser {{user}} docker
    sudo: yes
    tags: setup

  - shell: curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose  && chmod +x /usr/local/bin/docker-compose
    sudo: yes
    tags: setup

  - name: .bash_aliases
    copy: src=./templates/bash_aliases dest=/home/{{user}}/.bash_aliases owner={{user}} group={{user}} mode=0600
    tags: setup

  - name: .tmux.conf
    copy: src=./templates/tmux.conf dest=/home/{{user}}/.tmux.conf owner={{user}} group={{user}} mode=0600
    tags: setup

  - name: .vimrc
    copy: src=./templates/vimrc dest=/home/{{user}}/.vimrc owner={{user}} group={{user}} mode=0600
    tags: setup

  - name: .vim
    copy: src=./templates/vim/* dest=/home/{{user}}/.vim/* owner={{user}} group={{user}} mode=0600
    tags: setup

  # - name: known_hosts file
  #   copy: src=../templates/known_hosts dest=/home/{{user}}/.ssh/known_hosts owner={{user}} group={{user}} mode=0644
  #   tags: setup

  # - name: rsa private key for github
  #   copy: src=../templates/git-deploy dest=/home/{{user}}/.ssh/id_rsa owner={{user}} group={{user}} mode=0600
  #   tags: setup
