---
- hosts: server
  gather_facts: no
  sudo: no
  vars:
    user: dev
    password: $6$x.95LIU4dS$4WLX7ATLFUkAwMtTAJqrIcchJPIJZgsNQ1iUhyNrzOqvyr0P3QhcP5V8WLWrsFEZOlPV7aTAownXqzLmlul6x1

  tasks:
  - name: create group
    group: name={{user}} state=present
    tags: setup

  - name: create user
    user: name={{user}} state=present home=/home/{{user}} group={{user}} groups="sudo" password={{ password }} shell=/bin/bash
    tags: setup

  - name: install debian packages
    apt: pkg={{ item }} state=present update_cache=yes
    with_items:
    - git
    sudo: yes
    tags: setup

  - shell: curl -sSL https://get.docker.com/ubuntu/ | sudo sh
    sudo: yes
    tags: setup

  - command: adduser {{user}} docker
    sudo: yes
    tags: setup

  - shell: curl -L https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose  && chmod +x /usr/local/bin/docker-compose
    sudo: yes
    tags: setup

  - name: home folder
    copy: src=./home/ dest=/home/{{user}}/ owner={{user}} group={{user}} mode=0600
    tags: setup2
